name: Git Pull Deployment (via Tailscale)

on:
  push:
    branches:
      - main # or your primary branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to Tailscale network
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - name: Deploy via Tailscale SSH
        run: |
          ssh -o "StrictHostKeyChecking no" jason@coolify-server "
            cd ~/EbookLanguageLearningTest/
            if [ -d "./EbookLanguageLearningTest" ]; then
              echo "Directory exists. Pulling latest changes..."
              cd EbookLanguageLearning
              git pull origin main
            else
              echo "Directory does not exist. Cloning repository..."
              git clone https://github.com/JasonSteving99/EbookLanguageLearning.git
            fi
          "
